var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-state borders
		'lakesColor':'#ACE9FC', // lakes color
		'namesColor':'#ffffff', //color of short names
		//'mapShadow':'#000', //shadow color below the map
		//'shadowOpacity':'50', //shadow opacity, value, 0-100
		//'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		//'hover': 'ALABAMA', //state hover content
		'url':'/golf-courses/Alabama.html', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#4668af', //state's color when page loads
		//'overColor':'#FFEE88', //state's color when mouse hover
		//'downColor':'#FFEE88',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		//'hover': 'ALASKA',
		'url':'/golf-courses/Alaska.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_3':{
		//'hover': 'ARIZONA',
		'url':'/golf-courses/Arizona.html',
		'target':'same_window',
		'upColor':'#708bc0',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		//'hover': 'ARKANSAS',
		'url':'/golf-courses/Arkansas.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		//'hover': 'CALIFORNIA',
		'url':'/golf-courses/California.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		//'hover': 'COLORADO',
		'url':'/golf-courses/Colorado.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		//'hover': 'CONNECTICUT',
		'url':'/golf-courses/Connecticut.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		//'hover': 'DELAWARE',
		'url':'/golf-courses/Deleware.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_9':{
		//'hover': 'FLORIDA',
		'url':'/golf-courses/Florida.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_10':{
		//'hover': 'GEORGIA',
		'url':'/golf-courses/Georgia.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_11':{
		//'hover': 'HAWAII',
		'url':'/golf-courses/Hawaii.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		//'hover': 'IDAHO',
		'url':'/golf-courses/Idaho.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		//'hover': 'ILLINOIS',
		'url':'/golf-courses/Illinois.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		//'hover': 'INDIANA',
		'url':'/golf-courses/Indiana.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		//'hover': 'IOWA',
		'url':'/golf-courses/Iowa.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		//'hover': 'KANSAS',
		'url':'/golf-courses/Kansas.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		//'hover': 'KENTUCKY',
		'url':'/golf-courses/Kentucky.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_18':{
		//'hover': 'LOUISIANA',
		'url':'/golf-courses/Louisiana.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_19':{
		//'hover': 'MAINE',
		'url':'/golf-courses/Maine.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_20':{
		//'hover': 'MARYLAND',
		'url':'/golf-courses/Maryland.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		//'hover': 'MASSACHUSETTS',
		'url':'/golf-courses/Massachusetts.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_22':{
		//'hover': 'MICHIGAN',
		'url':'/golf-courses/Michigan.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		//'hover': 'MINNESOTA',
		'url':'/golf-courses/Minnesota.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		//'hover': 'MISSISSIPPI',
		'url':'/golf-courses/Mississippi.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_25':{
		//'hover': 'MISSOURI',
		'url':'/golf-courses/Missouri.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_26':{
		//'hover': 'MONTANA',
		'url':'/golf-courses/Montana.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		//'hover': 'NEBRASKA',
		'url':'/golf-courses/Nebraska.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		//'hover': 'NEVADA',
		'url':'/golf-courses/Nevada.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88', 
		//'downColor':'#993366',
		'enable':true,
	},
	'map_29':{
		//'hover': 'NEW HAMPSHIRE',
		'url':'/golf-courses/New-Hampshire.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		//'hover': 'NEW JERSEY',
		'url':'/golf-courses/New-Jersey.html',
		'target':'same_window',
		'upColor':'#708bc0',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_31':{
		//'hover': 'NEW MEXICO',
		'url':'/golf-courses/New-Mexico.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_32':{
		//'hover': 'NEW YORK',
		'url':'/golf-courses/New-York.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_33':{
		//'hover': 'NORTH CAROLINA',
		'url':'/golf-courses/North-Carolina.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_34':{
		//'hover': 'NORTH DAKOTA',
		'url':'/golf-courses/North-Dakota.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		//'hover': 'OHIO',
		'url':'/golf-courses/Ohio.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		//'hover': 'OKLAHOMA',
		'url':'/golf-courses/Oklahoma.html',
		'target':'same_window',
		'upColor':'#708bc0',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_37':{
		//'hover': 'OREGON',
		'url':'/golf-courses/Oregon.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_38':{
		//'hover': 'PENNSYLVANIA',
		'url':'/golf-courses/Pennsylvania.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_39':{
		//'hover': 'RHODE ISLAND',
		'url':'/golf-courses/Rhode-Island.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_40':{
		//'hover': 'SOUTH CAROLINA',
		'url':'/golf-courses/South-Carolina.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#FFEE88',
		'enable':true,
	},
	'map_41':{
		//'hover': 'SOUTH DAKOTA',
		'url':'/golf-courses/South-Dakota.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#FFEE88',
		'enable':true,
	},
	'map_42':{
		//'hover': 'TENNESSEE',
		'url':'/golf-courses/Tennessee.html',
		'target':'same_window',
		'upColor':'#708bc0',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_43':{
		//'hover': 'TEXAS',
		'url':'/golf-courses/Texas.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_44':{
		//'hover': 'UTAH',
		'url':'/golf-courses/Utah.html',
		'target':'same_window',
		'upColor':'#27429b',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_45':{
		//'hover': 'VERMONT',
		'url':'/golf-courses/Vermont.html',
		'target':'same_window',
		'upColor':'#708bc0',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_46':{
		//'hover': 'VIRGINIA',
		'url':'/golf-courses/Virginia.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_47':{
		//'hover': 'WASHINGTON',
		'url':'/golf-courses/Washington.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_48':{
		//'hover': 'WEST VIRGINIA',
		'url':'/golf-courses/West-Virginia.html',
		'target':'same_window',
		'upColor':'#708bc0',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_49':{
		//'hover': 'WISCONSIN',
		'url':'/golf-courses/Wisconsin.html',
		'target':'same_window',
		'upColor':'#4668af',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
	'map_50':{
		//'hover': 'WYOMING',
		'url':'/golf-courses/Wyoming.html',
		'target':'same_window',
		'upColor':'#092e72',
		//'overColor':'#FFEE88',
		//'downColor':'#993366',
		'enable':true,
	},
}
